[package]
name = "worker-help"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.7.4"
app = { path = "../app", features = ["ssr"] }
leptos = { version = "0.6.15", features = ["ssr"] }
leptos_router = { version = "0.6.15"}
